# version: '3.1'



version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo-network

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-network
    # command: ["odoo", "-d", "odoo", "-i", "base", "--stop-after-init"]  # only for first-time setup
    command: ["--", "-i", "base"]
    #command: ["odoo", "-d", "odoo", "-u", "money_management", "--without-demo-all"]

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo-network:




# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: odoo
#       POSTGRES_USER: odoo
#       POSTGRES_PASSWORD: odoo
#     volumes:
#       - odoo-db-data:/var/lib/postgresql/data
#     ports:
#       - "5433:5432"
#     networks:
#       - odoo-network

#   odoo:
#     image: odoo:17
#     depends_on:
#       - db
#     ports:
#       - "8069:8069"
#     volumes:
#       - odoo-web-data:/var/lib/odoo
#       - ./addons:/mnt/extra-addons
#       - ./config/odoo.conf:/etc/odoo/odoo.conf
#     networks:
#       - odoo-network
#     command: ["odoo", "-d", "odoo", "-i", "base", "--stop-after-init"] #first time
#     #command: ["--", "-i", "base"]
#     #command: ["odoo", "-d", "odoo", "-u", "money_management", "--without-demo-all"]

# volumes:
#   odoo-db-data:
#   odoo-web-data:

# networks:
#   odoo-network: